DEPARTMENTS = [
    "Executive Leadership",
    "Human Resources",
    "Finance & Accounting",
    "Information Technology",
    "Marketing",
    "Sales",
    "Operations",
    "Customer Service",
    "Legal & Compliance",
    "Research & Development",
    "Product Management",
    "Engineering",
    "Supply Chain & Logistics",
    "Quality Assurance",
    "Training & Development",
    "Communications",
    "Facilities & Administration",
    "Data & Analytics",
    "Project Management Office",
    "Other",
]
